<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="social event" nsURI="http://social event/1.0" nsPrefix="social event">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Event">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//EventType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfPartecipants" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="People">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gender" eType="#//Gender"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nationality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="friend of" upperBound="-1"
        eType="#//People"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="friendOf" lowerBound="1"
        upperBound="-1" eType="#//People"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Post">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Media"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="media" upperBound="-1"
        eType="#//Media" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hashtag" upperBound="-1"
        eType="#//Hashtag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tags" upperBound="-1" eType="#//People"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date&amp;hour" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="socialNetwork" eType="#//SN%20Type"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="author" lowerBound="1"
        eType="#//People"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference2" eType="#//Post"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shares" eType="#//Post"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="related to" lowerBound="1"
        eType="#//Event"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="like" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfShare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedTo" lowerBound="1"
        eType="#//Event"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EventType">
    <eLiterals name="birthday"/>
    <eLiterals name="meeting" value="1"/>
    <eLiterals name="conference" value="2"/>
    <eLiterals name="festival" value="3"/>
    <eLiterals name="seminar" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Gender">
    <eLiterals name="male"/>
    <eLiterals name="female" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Media" eSuperTypes="#//EClass2">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Post"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hashtag">
    <eStructuralFeatures xsi:type="ecore:EReference" name="EReference0" eType="#//Post"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EClass2"/>
  <eClassifiers xsi:type="ecore:EClass" name="Video" eSuperTypes="#//Media">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Photo" eSuperTypes="#//Media"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SN Type">
    <eLiterals name="Facebook"/>
    <eLiterals name="Twitter" value="1"/>
    <eLiterals name="Instagram" value="2"/>
  </eClassifiers>
</ecore:EPackage>
